export const dashboardText = {
  ru: {
    settings: 'Настройки аккаунта', closeSettings: 'Закрыть настройки',
    title: 'Личный кабинет', telegramAccount: 'Аккаунт Telegram',
    subscription: 'Текущая подписка', active: 'Активна', inactive: 'Неактивна',
    expires: 'Действует до', remaining: 'Осталось', days: 'дн.', renew: 'Продлить',
    devices: 'Устройства', deviceStats: 'Статистика подключённых устройств', connected: 'Подключено устройств',
    deviceOnboarding: 'Подключение устройств', quickConnection: 'Быстрое подключение',
    quickConnectionNote: 'Выберите клиент для импорта доступа к VPN.',
    clients: { happ: 'Happ', incy: 'INCY' },
    openClient: 'Открыть {client}', choosePlan: 'Выбрать тариф',
    happDescription: 'Открыть доступ в Happ по выданной ссылке.',
    incyDescription: 'Импортировать подписку в INCY.',
    connectAnother: 'Подключить другое устройство', anotherDeviceNote: 'Выберите устройство и клиент — проведём вас по шагам подключения.',
    myDevices: 'Мои устройства', deviceCount: '{used} из {limit}',
    previewUsage: 'Предварительные данные',
    wizardTitle: 'Подключить устройство', wizardStep: 'Шаг {step} из 3',
    choosePlatform: 'Выберите устройство', chooseClient: 'Установите и выберите клиент', setupDevice: 'Подключение',
    installClientNote: 'Установите клиент для {platform} или выберите уже установленный. Загрузка клиента не подключает VPN.',
    downloadLabels: { appStore: 'App Store', appStoreRu: 'App Store (RU)', googlePlay: 'Google Play', windowsX64: 'Скачать для Windows (x64)', windowsDownload: 'Скачать для Windows', linuxDownloads: 'Загрузки для Linux' },
    openInApp: 'ОТКРЫТЬ В ПРИЛОЖЕНИИ', copySubscriptionLink: 'КОПИРОВАТЬ ССЫЛКУ ПОДПИСКИ', showQr: 'ПОКАЗАТЬ QR',
    qrUnavailable: 'QR-код пока недоступен.', linkCopied: 'Ссылка подписки скопирована.', linkCopyFailed: 'Не удалось скопировать ссылку. Разрешите доступ к буферу обмена и попробуйте снова.',
    resetDevice: 'СБРОСИТЬ', resetAllDevices: 'СБРОСИТЬ ВСЕ УСТРОЙСТВА', resetDevicesNote: 'Сброс станет доступен после подключения управления VPN-устройствами.',
    platforms: { ios: 'iPhone / iPad', android: 'Android', windows: 'Windows', macos: 'macOS', linux: 'Linux' },
    setupInstall: 'Установите {client} на устройство {platform} из официального источника клиента.',
    setupImport: 'Нажмите кнопку ниже, чтобы передать выданный доступ в клиент.',
    setupEnable: 'После импорта включите VPN в самом клиенте и подтвердите системный запрос, если он появится.',
    wizardBack: 'Назад', wizardNext: 'Далее', closeDialog: 'Закрыть',
    accessNotIssued: 'Доступ к VPN ещё не выдан',
    accessNotIssuedNote: 'Подписка активна, но ссылка для выбранного клиента пока недоступна. Подключение станет доступно после выдачи доступа.',
    clientHandoff: 'Продолжите в клиенте', clientHandoffNote: 'Если клиент не открылся, проверьте, что он установлен. Импорт ссылки сам по себе не включает VPN.',
    clientOpenFailed: 'Не удалось открыть клиент', clientOpenFailedNote: 'Проверьте, что клиент установлен, и попробуйте ещё раз.',
    weeklyUsage: 'За эту неделю', usageThisWeek: 'Защищённый трафик через VPN', trafficOverview: 'Трафик', vpnUsage: 'Использование VPN', lastSevenDays: '7 дней', vpnActive: 'VPN активен', addDevice: 'Подключить устройство', online: 'В сети', offline: 'Не в сети', used: 'Использовано', lastActive: 'Последняя активность', manageDevice: 'Настроить устройство',
    noDevices: 'У вас пока нет подключённых устройств.', firstDevice: 'Откройте управление для первого подключения.',
    manage: 'Управлять', balance: 'Баланс', topUp: 'Пополнить', topUpSoon: 'Пополнение баланса скоро появится.',
    referrals: 'Реферальная программа', invited: 'Приглашено друзей', bonus: 'Бонусы', details: 'Подробнее',
    support: 'Поддержка', help: 'Поможем с подключением и ответим на вопросы о сервисе.',
    contact: 'Открыть поддержку', supportRequests: 'Мои обращения', newRequest: 'Новое обращение',
    noRequests: 'У вас пока нет обращений.', supportIntro: 'Опишите проблему, и команда поддержки ответит вам здесь.',
    category: 'Тема обращения', message: 'Сообщение', messagePlaceholder: 'Опишите вопрос или проблему…',
    send: 'Отправить', sending: 'Отправляем…', supportLoadError: 'Не удалось загрузить обращения.',
    supportSendError: 'Не удалось отправить сообщение.', supportTeam: 'Поддержка', you: 'Вы', loading: 'Загрузка…',
    categories: { connection: 'Подключение', payment: 'Оплата', account: 'Аккаунт', other: 'Другое' },
    statuses: { open: 'Открыто', waiting_user: 'Ответ поддержки', closed: 'Закрыто' },
    plans: 'Тарифы', terms: 'Пользовательское соглашение', privacy: 'Политика конфиденциальности',
    preparing: 'Раздел готовится', preparingNote: 'Здесь скоро появится новая информация.', back: 'Вернуться в кабинет',
    legalLinks: 'Правовая информация',
  },
  en: {
    settings: 'Account settings', closeSettings: 'Close settings',
    title: 'Your Account', telegramAccount: 'Telegram account',
    subscription: 'Current subscription', active: 'Active', inactive: 'Inactive',
    expires: 'Valid until', remaining: 'Remaining', days: 'days', renew: 'Renew',
    devices: 'Devices', deviceStats: 'Connected device statistics', connected: 'Connected devices',
    deviceOnboarding: 'Connect your devices', quickConnection: 'Quick connection',
    quickConnectionNote: 'Choose a client to import your VPN access.',
    clients: { happ: 'Happ', incy: 'INCY' },
    openClient: 'Open {client}', choosePlan: 'Choose a plan',
    happDescription: 'Open your access in Happ using an issued link.',
    incyDescription: 'Import your subscription into INCY.',
    connectAnother: 'Connect another device', anotherDeviceNote: 'Choose your device and client — we will guide you through the setup.',
    myDevices: 'My devices', deviceCount: '{used} of {limit}',
    previewUsage: 'Preview data',
    wizardTitle: 'Connect a device', wizardStep: 'Step {step} of 3',
    choosePlatform: 'Choose your device', chooseClient: 'Install and choose your client', setupDevice: 'Connection',
    installClientNote: 'Install a client for {platform}, or choose one you already have. Downloading a client does not connect VPN.',
    downloadLabels: { appStore: 'App Store', appStoreRu: 'App Store (RU)', googlePlay: 'Google Play', windowsX64: 'Download for Windows (x64)', windowsDownload: 'Download for Windows', linuxDownloads: 'Linux downloads' },
    openInApp: 'OPEN IN APP', copySubscriptionLink: 'COPY SUBSCRIPTION LINK', showQr: 'SHOW QR',
    qrUnavailable: 'QR code is not available yet.', linkCopied: 'Subscription link copied.', linkCopyFailed: 'Could not copy the link. Allow clipboard access and try again.',
    resetDevice: 'RESET', resetAllDevices: 'RESET ALL DEVICES', resetDevicesNote: 'Device reset will be available once VPN device management is connected.',
    platforms: { ios: 'iPhone / iPad', android: 'Android', windows: 'Windows', macos: 'macOS', linux: 'Linux' },
    setupInstall: 'Install {client} on your {platform} device from the client’s official source.',
    setupImport: 'Use the button below to hand your issued access to the client.',
    setupEnable: 'After importing, turn on VPN in the client and confirm the system prompt if it appears.',
    wizardBack: 'Back', wizardNext: 'Next', closeDialog: 'Close',
    accessNotIssued: 'VPN access has not been issued yet',
    accessNotIssuedNote: 'Your subscription is active, but a link for this client is not available yet. You can connect once access has been issued.',
    clientHandoff: 'Continue in the client', clientHandoffNote: 'If the client did not open, check that it is installed. Importing a link does not turn on VPN by itself.',
    clientOpenFailed: 'Could not open the client', clientOpenFailedNote: 'Check that the client is installed and try again.',
    weeklyUsage: 'This week', usageThisWeek: 'Protected traffic through VPN', trafficOverview: 'Traffic', vpnUsage: 'VPN usage', lastSevenDays: '7 days', vpnActive: 'VPN active', addDevice: 'Connect device', online: 'Online', offline: 'Offline', used: 'Used', lastActive: 'Last active', manageDevice: 'Manage device',
    noDevices: 'No devices connected yet.', firstDevice: 'Open device management to connect your first device.',
    manage: 'Manage', balance: 'Balance', topUp: 'Top up', topUpSoon: 'Balance top-ups are coming soon.',
    referrals: 'Referral program', invited: 'Friends invited', bonus: 'Bonuses', details: 'Learn more',
    support: 'Support', help: 'Get help connecting your devices and answers to questions about the service.',
    contact: 'Open support', supportRequests: 'My requests', newRequest: 'New request',
    noRequests: 'You have no support requests yet.', supportIntro: 'Describe your issue and the support team will reply here.',
    category: 'Request topic', message: 'Message', messagePlaceholder: 'Describe your question or issue…',
    send: 'Send', sending: 'Sending…', supportLoadError: 'Could not load your requests.',
    supportSendError: 'Could not send your message.', supportTeam: 'Support team', you: 'You', loading: 'Loading…',
    categories: { connection: 'Connection', payment: 'Payment', account: 'Account', other: 'Other' },
    statuses: { open: 'Open', waiting_user: 'Support replied', closed: 'Closed' },
    plans: 'Plans', terms: 'Terms of service', privacy: 'Privacy policy',
    preparing: 'This section is being prepared', preparingNote: 'New information will be available here soon.', back: 'Back to dashboard',
    legalLinks: 'Legal information',
  },
}

export const dashboardPlaceholderRoutes = ['devices', 'referrals', 'privacy', 'terms']
