export const dashboardText = {
  ru: {
    settings: 'Настройки аккаунта', closeSettings: 'Закрыть настройки',
    title: 'Личный кабинет', telegramAccount: 'Аккаунт Telegram',
    subscription: 'Текущая подписка', active: 'Активна', inactive: 'Неактивна',
    expires: 'Действует до', remaining: 'Осталось', days: 'дн.', renew: 'Продлить',
    devices: 'Устройства', deviceStats: 'Статистика подключённых устройств', connected: 'Подключено устройств',
    weeklyUsage: 'За эту неделю', usageThisWeek: 'Защищённый трафик через VPN', trafficOverview: 'Трафик', vpnUsage: 'Использование VPN', lastSevenDays: '7 дней', vpnActive: 'VPN активен', addDevice: 'Подключить устройство', online: 'В сети', offline: 'Не в сети', used: 'Использовано', lastActive: 'Последняя активность', manageDevice: 'Настроить устройство',
    noDevices: 'У вас пока нет подключённых устройств.', firstDevice: 'Откройте управление для первого подключения.',
    manage: 'Управлять', balance: 'Баланс', topUp: 'Пополнить', topUpSoon: 'Пополнение баланса скоро появится.',
    referrals: 'Реферальная программа', invited: 'Приглашено друзей', bonus: 'Бонусы', details: 'Подробнее',
    support: 'Поддержка', help: 'Поможем с подключением и ответим на вопросы о сервисе.',
    contact: 'Открыть поддержку', supportRequests: 'Мои обращения', newRequest: 'Новое обращение',
    noRequests: 'У вас пока нет обращений.', supportIntro: 'Опишите проблему, и команда поддержки ответит вам здесь.',
    category: 'Тема обращения', message: 'Сообщение', messagePlaceholder: 'Опишите вопрос или проблему…',
    send: 'Отправить', sending: 'Отправляем…', supportLoadError: 'Не удалось загрузить обращения.',
    supportSendError: 'Не удалось отправить сообщение.', supportTeam: 'Поддержка', you: 'Вы', loading: 'Загрузка…',
    categories: { connection: 'Подключение', payment: 'Оплата', account: 'Аккаунт', other: 'Другое' },
    statuses: { open: 'Открыто', waiting_user: 'Ответ поддержки', closed: 'Закрыто' },
    plans: 'Тарифы', terms: 'Пользовательское соглашение', privacy: 'Политика конфиденциальности',
    preparing: 'Раздел готовится', preparingNote: 'Здесь скоро появится новая информация.', back: 'Вернуться в кабинет',
    legalLinks: 'Правовая информация',
  },
  en: {
    settings: 'Account settings', closeSettings: 'Close settings',
    title: 'Your Account', telegramAccount: 'Telegram account',
    subscription: 'Current subscription', active: 'Active', inactive: 'Inactive',
    expires: 'Valid until', remaining: 'Remaining', days: 'days', renew: 'Renew',
    devices: 'Devices', deviceStats: 'Connected device statistics', connected: 'Connected devices',
    weeklyUsage: 'This week', usageThisWeek: 'Protected traffic through VPN', trafficOverview: 'Traffic', vpnUsage: 'VPN usage', lastSevenDays: '7 days', vpnActive: 'VPN active', addDevice: 'Connect device', online: 'Online', offline: 'Offline', used: 'Used', lastActive: 'Last active', manageDevice: 'Manage device',
    noDevices: 'No devices connected yet.', firstDevice: 'Open device management to connect your first device.',
    manage: 'Manage', balance: 'Balance', topUp: 'Top up', topUpSoon: 'Balance top-ups are coming soon.',
    referrals: 'Referral program', invited: 'Friends invited', bonus: 'Bonuses', details: 'Learn more',
    support: 'Support', help: 'Get help connecting your devices and answers to questions about the service.',
    contact: 'Open support', supportRequests: 'My requests', newRequest: 'New request',
    noRequests: 'You have no support requests yet.', supportIntro: 'Describe your issue and the support team will reply here.',
    category: 'Request topic', message: 'Message', messagePlaceholder: 'Describe your question or issue…',
    send: 'Send', sending: 'Sending…', supportLoadError: 'Could not load your requests.',
    supportSendError: 'Could not send your message.', supportTeam: 'Support team', you: 'You', loading: 'Loading…',
    categories: { connection: 'Connection', payment: 'Payment', account: 'Account', other: 'Other' },
    statuses: { open: 'Open', waiting_user: 'Support replied', closed: 'Closed' },
    plans: 'Plans', terms: 'Terms of service', privacy: 'Privacy policy',
    preparing: 'This section is being prepared', preparingNote: 'New information will be available here soon.', back: 'Back to dashboard',
    legalLinks: 'Legal information',
  },
}

export const dashboardPlaceholderRoutes = ['devices', 'referrals', 'privacy', 'terms']
